/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "SensorMessagePack.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MagData, MagData, AUTO)


PB_BIND(AccelData, AccelData, AUTO)


PB_BIND(GyroData, GyroData, AUTO)


PB_BIND(ColorData, ColorData, AUTO)


PB_BIND(GestureProxData, GestureProxData, AUTO)


PB_BIND(TempHumData, TempHumData, AUTO)


PB_BIND(SensorMessage, SensorMessage, AUTO)
