/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_SENSORMESSAGEPACK_SENSORMESSAGEPACK_PB_H_INCLUDED
#define PB_SENSORMESSAGEPACK_SENSORMESSAGEPACK_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AccelData {
    float x;
    float y;
    float z;
} AccelData;

typedef struct _ColorData {
    int32_t r;
    int32_t g;
    int32_t b;
} ColorData;

typedef struct _GestureProxData {
    int32_t gesture;
    int32_t proximity;
} GestureProxData;

typedef struct _GyroData {
    float x;
    float y;
    float z;
} GyroData;

typedef struct _MagData {
    float x;
    float y;
    float z;
} MagData;

typedef struct _TempHumData {
    float tempurature;
    float humidity;
} TempHumData;

typedef struct _SensorMessage {
    bool has_mag_dat;
    MagData mag_dat;
    bool has_accel_dat;
    AccelData accel_dat;
    bool has_gyro_dat;
    GyroData gyro_dat;
    bool has_color_dat;
    ColorData color_dat;
    bool has_gest_prox_dat;
    GestureProxData gest_prox_dat;
    bool has_temp_hum_dat;
    TempHumData temp_hum_dat;
} SensorMessage;


/* Initializer values for message structs */
#define MagData_init_default                     {0, 0, 0}
#define AccelData_init_default                   {0, 0, 0}
#define GyroData_init_default                    {0, 0, 0}
#define ColorData_init_default                   {0, 0, 0}
#define GestureProxData_init_default             {0, 0}
#define TempHumData_init_default                 {0, 0}
#define SensorMessage_init_default               {false, MagData_init_default, false, AccelData_init_default, false, GyroData_init_default, false, ColorData_init_default, false, GestureProxData_init_default, false, TempHumData_init_default}
#define MagData_init_zero                        {0, 0, 0}
#define AccelData_init_zero                      {0, 0, 0}
#define GyroData_init_zero                       {0, 0, 0}
#define ColorData_init_zero                      {0, 0, 0}
#define GestureProxData_init_zero                {0, 0}
#define TempHumData_init_zero                    {0, 0}
#define SensorMessage_init_zero                  {false, MagData_init_zero, false, AccelData_init_zero, false, GyroData_init_zero, false, ColorData_init_zero, false, GestureProxData_init_zero, false, TempHumData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AccelData_x_tag                          1
#define AccelData_y_tag                          2
#define AccelData_z_tag                          3
#define ColorData_r_tag                          1
#define ColorData_g_tag                          2
#define ColorData_b_tag                          3
#define GestureProxData_gesture_tag              1
#define GestureProxData_proximity_tag            2
#define GyroData_x_tag                           1
#define GyroData_y_tag                           2
#define GyroData_z_tag                           3
#define MagData_x_tag                            1
#define MagData_y_tag                            2
#define MagData_z_tag                            3
#define TempHumData_tempurature_tag              1
#define TempHumData_humidity_tag                 2
#define SensorMessage_mag_dat_tag                1
#define SensorMessage_accel_dat_tag              2
#define SensorMessage_gyro_dat_tag               3
#define SensorMessage_color_dat_tag              4
#define SensorMessage_gest_prox_dat_tag          5
#define SensorMessage_temp_hum_dat_tag           6

/* Struct field encoding specification for nanopb */
#define MagData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define MagData_CALLBACK NULL
#define MagData_DEFAULT NULL

#define AccelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define AccelData_CALLBACK NULL
#define AccelData_DEFAULT NULL

#define GyroData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define GyroData_CALLBACK NULL
#define GyroData_DEFAULT NULL

#define ColorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    r,                 1) \
X(a, STATIC,   SINGULAR, INT32,    g,                 2) \
X(a, STATIC,   SINGULAR, INT32,    b,                 3)
#define ColorData_CALLBACK NULL
#define ColorData_DEFAULT NULL

#define GestureProxData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    gesture,           1) \
X(a, STATIC,   SINGULAR, INT32,    proximity,         2)
#define GestureProxData_CALLBACK NULL
#define GestureProxData_DEFAULT NULL

#define TempHumData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    tempurature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2)
#define TempHumData_CALLBACK NULL
#define TempHumData_DEFAULT NULL

#define SensorMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mag_dat,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accel_dat,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gyro_dat,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color_dat,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gest_prox_dat,     5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  temp_hum_dat,      6)
#define SensorMessage_CALLBACK NULL
#define SensorMessage_DEFAULT NULL
#define SensorMessage_mag_dat_MSGTYPE MagData
#define SensorMessage_accel_dat_MSGTYPE AccelData
#define SensorMessage_gyro_dat_MSGTYPE GyroData
#define SensorMessage_color_dat_MSGTYPE ColorData
#define SensorMessage_gest_prox_dat_MSGTYPE GestureProxData
#define SensorMessage_temp_hum_dat_MSGTYPE TempHumData

extern const pb_msgdesc_t MagData_msg;
extern const pb_msgdesc_t AccelData_msg;
extern const pb_msgdesc_t GyroData_msg;
extern const pb_msgdesc_t ColorData_msg;
extern const pb_msgdesc_t GestureProxData_msg;
extern const pb_msgdesc_t TempHumData_msg;
extern const pb_msgdesc_t SensorMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MagData_fields &MagData_msg
#define AccelData_fields &AccelData_msg
#define GyroData_fields &GyroData_msg
#define ColorData_fields &ColorData_msg
#define GestureProxData_fields &GestureProxData_msg
#define TempHumData_fields &TempHumData_msg
#define SensorMessage_fields &SensorMessage_msg

/* Maximum encoded size of messages (where known) */
#define MagData_size                             15
#define AccelData_size                           15
#define GyroData_size                            15
#define ColorData_size                           33
#define GestureProxData_size                     22
#define TempHumData_size                         10
#define SensorMessage_size                       122

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
